# MySQL Docker database connection
spring.datasource.url=jdbc:mysql://localhost:33306/ces_db
spring.datasource.username=root
spring.datasource.password=mysqlpass

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
